#!/bin/sh

ADDONNAME=check_mk_agent
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${ADDON_DIR}/plugins
chmod 755 ${ADDON_DIR}/plugins
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

cp -af addon/* ${ADDON_DIR}
cp -af rc.d/* ${RCD_DIR}

sync
